import type {
  Campaign,
  Company,
  Contact,
  Deal,
  Devis,
  Task,
  WebsiteProject,
  Workflow,
} from "./types";
import { uid } from "./storage";

const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};
const daysFromNow = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
};

export function seedCompanies(): Company[] {
  return [
    {
      id: "co_atlas",
      name: "Atlas Retail Group",
      domain: "atlasretail.fr",
      industry: "E-commerce",
      size: "50-200",
      website: "https://atlasretail.fr",
      linkedin: "https://linkedin.com/company/atlas-retail",
      phone: "+33 1 42 00 11 22",
      city: "Paris",
      country: "France",
      tags: ["e-commerce", "retail"],
      notes: "Looking to revamp their online store and automate marketing.",
      createdAt: daysAgo(45),
    },
    {
      id: "co_norda",
      name: "Norda Architecture",
      domain: "norda-archi.com",
      industry: "Architecture",
      size: "10-50",
      website: "https://norda-archi.com",
      city: "Lyon",
      country: "France",
      tags: ["b2b", "design"],
      notes: "Needs a new portfolio site + CRM for client follow-up.",
      createdAt: daysAgo(38),
    },
    {
      id: "co_finstack",
      name: "FinStack Solutions",
      domain: "finstack.io",
      industry: "Fintech",
      size: "10-50",
      website: "https://finstack.io",
      city: "Remote",
      country: "Belgium",
      tags: ["saas", "fintech"],
      notes: "Found through Instantly campaign — interested in dashboard redesign.",
      createdAt: daysAgo(30),
    },
    {
      id: "co_verde",
      name: "Verde Bio Market",
      domain: "verdebio.fr",
      industry: "Food & Beverage",
      size: "1-10",
      website: "https://verdebio.fr",
      city: "Bordeaux",
      country: "France",
      tags: ["local-business"],
      createdAt: daysAgo(22),
    },
    {
      id: "co_pulse",
      name: "Pulse Fitness Club",
      domain: "pulsefitness.fr",
      industry: "Health & Wellness",
      size: "10-50",
      website: "https://pulsefitness.fr",
      city: "Marseille",
      country: "France",
      tags: ["local-business", "membership"],
      createdAt: daysAgo(15),
    },
    {
      id: "co_orbit",
      name: "Orbit Logistics",
      domain: "orbit-logistics.com",
      industry: "Logistics",
      size: "200-500",
      website: "https://orbit-logistics.com",
      city: "Lille",
      country: "France",
      tags: ["enterprise"],
      createdAt: daysAgo(8),
    },
  ];
}

export function seedContacts(): Contact[] {
  return [
    {
      id: "ct_marie",
      firstName: "Marie",
      lastName: "Dubois",
      email: "marie.dubois@atlasretail.fr",
      phone: "+33 6 12 34 56 78",
      jobTitle: "Head of E-commerce",
      companyId: "co_atlas",
      source: "LGM",
      status: "qualified",
      tags: ["decision-maker"],
      notes: "Very responsive on LinkedIn. Wants a proposal by end of month.",
      createdAt: daysAgo(40),
      lastContactedAt: daysAgo(2),
    },
    {
      id: "ct_thomas",
      firstName: "Thomas",
      lastName: "Lefevre",
      email: "thomas@norda-archi.com",
      jobTitle: "Founding Partner",
      companyId: "co_norda",
      source: "Referral",
      status: "prospect",
      tags: [],
      createdAt: daysAgo(35),
      lastContactedAt: daysAgo(5),
    },
    {
      id: "ct_julien",
      firstName: "Julien",
      lastName: "Moreau",
      email: "j.moreau@finstack.io",
      jobTitle: "Product Manager",
      companyId: "co_finstack",
      source: "Instantly",
      status: "qualified",
      tags: ["warm"],
      createdAt: daysAgo(28),
      lastContactedAt: daysAgo(1),
    },
    {
      id: "ct_celine",
      firstName: "Celine",
      lastName: "Garnier",
      email: "celine@verdebio.fr",
      jobTitle: "Owner",
      companyId: "co_verde",
      source: "Website",
      status: "customer",
      tags: ["repeat-client"],
      createdAt: daysAgo(20),
      lastContactedAt: daysAgo(10),
    },
    {
      id: "ct_karim",
      firstName: "Karim",
      lastName: "Benali",
      email: "karim@pulsefitness.fr",
      jobTitle: "Marketing Manager",
      companyId: "co_pulse",
      source: "LGM",
      status: "lead",
      tags: [],
      createdAt: daysAgo(12),
    },
    {
      id: "ct_sophie",
      firstName: "Sophie",
      lastName: "Renard",
      email: "s.renard@orbit-logistics.com",
      jobTitle: "Digital Transformation Lead",
      companyId: "co_orbit",
      source: "Instantly",
      status: "lead",
      tags: ["enterprise"],
      createdAt: daysAgo(5),
    },
    {
      id: "ct_paul",
      firstName: "Paul",
      lastName: "Girard",
      email: "paul.girard@gmail.com",
      jobTitle: "Independent Consultant",
      source: "LinkedIn",
      status: "lost",
      tags: [],
      notes: "Went with a cheaper agency.",
      createdAt: daysAgo(50),
      lastContactedAt: daysAgo(20),
    },
  ];
}

export function seedDeals(): Deal[] {
  return [
    {
      id: "dl_atlas_redesign",
      name: "Atlas Retail — E-commerce Redesign",
      companyId: "co_atlas",
      contactId: "ct_marie",
      value: 8500,
      currency: "EUR",
      stage: "proposal",
      probability: 60,
      expectedCloseDate: daysFromNow(10),
      source: "LGM",
      notes: "Devis sent, waiting for validation from finance team.",
      createdAt: daysAgo(20),
      cost: 1200,
    },
    {
      id: "dl_norda_site",
      name: "Norda — Portfolio Website",
      companyId: "co_norda",
      contactId: "ct_thomas",
      value: 4200,
      currency: "EUR",
      stage: "negotiation",
      probability: 70,
      expectedCloseDate: daysFromNow(5),
      source: "Referral",
      createdAt: daysAgo(25),
      cost: 600,
    },
    {
      id: "dl_finstack_dashboard",
      name: "FinStack — Dashboard UI Revamp",
      companyId: "co_finstack",
      contactId: "ct_julien",
      value: 12000,
      currency: "EUR",
      stage: "qualified",
      probability: 40,
      expectedCloseDate: daysFromNow(25),
      source: "Instantly",
      createdAt: daysAgo(15),
      cost: 2000,
    },
    {
      id: "dl_verde_maintenance",
      name: "Verde Bio — Monthly Maintenance",
      companyId: "co_verde",
      contactId: "ct_celine",
      value: 350,
      currency: "EUR",
      stage: "won",
      probability: 100,
      expectedCloseDate: daysAgo(5),
      closedAt: daysAgo(5),
      source: "Website",
      createdAt: daysAgo(18),
      cost: 50,
    },
    {
      id: "dl_pulse_landing",
      name: "Pulse Fitness — Landing Page + Ads",
      companyId: "co_pulse",
      contactId: "ct_karim",
      value: 2100,
      currency: "EUR",
      stage: "contacted",
      probability: 20,
      expectedCloseDate: daysFromNow(20),
      source: "LGM",
      createdAt: daysAgo(8),
      cost: 0,
    },
    {
      id: "dl_orbit_platform",
      name: "Orbit Logistics — Internal Tools Audit",
      companyId: "co_orbit",
      contactId: "ct_sophie",
      value: 18000,
      currency: "EUR",
      stage: "new",
      probability: 10,
      expectedCloseDate: daysFromNow(45),
      source: "Instantly",
      createdAt: daysAgo(4),
      cost: 0,
    },
    {
      id: "dl_paul_lost",
      name: "Paul Girard — Personal Brand Site",
      contactId: "ct_paul",
      value: 1500,
      currency: "EUR",
      stage: "lost",
      probability: 0,
      source: "LinkedIn",
      createdAt: daysAgo(48),
      closedAt: daysAgo(20),
      lostReason: "Budget — chose a cheaper provider",
      cost: 80,
    },
  ];
}

export function seedDevis(): Devis[] {
  return [
    {
      id: "dv_2026_001",
      number: "DEVIS-2026-001",
      dealId: "dl_atlas_redesign",
      companyId: "co_atlas",
      contactId: "ct_marie",
      title: "Refonte site e-commerce Atlas Retail",
      status: "sent",
      issueDate: daysAgo(6),
      validUntil: daysFromNow(24),
      currency: "EUR",
      items: [
        { id: uid(), description: "UX/UI Design (10 pages)", quantity: 1, unitPrice: 3200, vatRate: 20 },
        { id: uid(), description: "Développement front-end React", quantity: 1, unitPrice: 4000, vatRate: 20 },
        { id: uid(), description: "Intégration paiement & SEO de base", quantity: 1, unitPrice: 1300, vatRate: 20 },
      ],
      notes: "Paiement en 2 fois : 50% à la signature, 50% à la livraison.",
      createdAt: daysAgo(6),
    },
    {
      id: "dv_2026_002",
      number: "DEVIS-2026-002",
      dealId: "dl_norda_site",
      companyId: "co_norda",
      contactId: "ct_thomas",
      title: "Site portfolio Norda Architecture",
      status: "accepted",
      issueDate: daysAgo(14),
      validUntil: daysAgo(0),
      currency: "EUR",
      items: [
        { id: uid(), description: "Design + Webflow build (6 pages)", quantity: 1, unitPrice: 3200, vatRate: 20 },
        { id: uid(), description: "Rédaction contenus + SEO", quantity: 1, unitPrice: 1000, vatRate: 20 },
      ],
      createdAt: daysAgo(14),
    },
    {
      id: "dv_2026_003",
      number: "DEVIS-2026-003",
      companyId: "co_verde",
      contactId: "ct_celine",
      title: "Maintenance mensuelle site Verde Bio",
      status: "accepted",
      issueDate: daysAgo(20),
      currency: "EUR",
      items: [
        { id: uid(), description: "Forfait maintenance mensuel", quantity: 1, unitPrice: 350, vatRate: 20 },
      ],
      createdAt: daysAgo(20),
    },
    {
      id: "dv_2026_004",
      number: "DEVIS-2026-004",
      companyId: "co_pulse",
      contactId: "ct_karim",
      title: "Landing page + campagne Ads — Pulse Fitness",
      status: "draft",
      issueDate: daysAgo(1),
      validUntil: daysFromNow(29),
      currency: "EUR",
      items: [
        { id: uid(), description: "Landing page haute conversion", quantity: 1, unitPrice: 1400, vatRate: 20 },
        { id: uid(), description: "Setup campagne Meta Ads", quantity: 1, unitPrice: 700, vatRate: 20 },
      ],
      createdAt: daysAgo(1),
    },
  ];
}

export function seedTasks(): Task[] {
  return [
    {
      id: "tk_1",
      title: "Relancer Marie (Atlas Retail) — devis e-commerce",
      type: "email",
      priority: "high",
      dueDate: daysFromNow(0),
      done: false,
      contactId: "ct_marie",
      companyId: "co_atlas",
      dealId: "dl_atlas_redesign",
      createdAt: daysAgo(2),
    },
    {
      id: "tk_2",
      title: "Appel découverte — Pulse Fitness",
      type: "call",
      priority: "medium",
      dueDate: daysFromNow(0),
      done: false,
      contactId: "ct_karim",
      companyId: "co_pulse",
      dealId: "dl_pulse_landing",
      createdAt: daysAgo(1),
    },
    {
      id: "tk_3",
      title: "Préparer proposition Orbit Logistics",
      type: "todo",
      priority: "high",
      dueDate: daysFromNow(1),
      done: false,
      companyId: "co_orbit",
      dealId: "dl_orbit_platform",
      createdAt: daysAgo(1),
    },
    {
      id: "tk_4",
      title: "Visio kickoff — Norda Architecture",
      type: "meeting",
      priority: "high",
      dueDate: daysFromNow(2),
      done: false,
      contactId: "ct_thomas",
      companyId: "co_norda",
      dealId: "dl_norda_site",
      createdAt: daysAgo(3),
    },
    {
      id: "tk_5",
      title: "Exporter rapport campagnes Instantly de la semaine",
      type: "todo",
      priority: "medium",
      dueDate: daysFromNow(3),
      done: false,
      createdAt: daysAgo(0),
    },
    {
      id: "tk_6",
      title: "Vérifier uptime + perf site Verde Bio",
      type: "todo",
      priority: "low",
      dueDate: daysFromNow(4),
      done: false,
      companyId: "co_verde",
      createdAt: daysAgo(0),
    },
    {
      id: "tk_7",
      title: "Envoyer facture maintenance Verde Bio",
      type: "todo",
      priority: "medium",
      dueDate: daysAgo(1),
      done: true,
      companyId: "co_verde",
      createdAt: daysAgo(6),
    },
    {
      id: "tk_8",
      title: "Suivre séquence LGM — prospects e-commerce Paris",
      type: "todo",
      priority: "medium",
      dueDate: daysFromNow(6),
      done: false,
      createdAt: daysAgo(0),
    },
  ];
}

export function seedCampaigns(): Campaign[] {
  return [
    {
      id: "cmp_lgm_ecommerce",
      name: "E-commerce FR — Décideurs LinkedIn",
      platform: "LGM",
      status: "active",
      startDate: daysAgo(30),
      contactsTargeted: 420,
      messagesSent: 1180,
      opened: 940,
      replied: 96,
      positiveReplies: 31,
      meetingsBooked: 9,
      notes: "Séquence en 4 étapes — visite profil, invite, message, follow-up.",
    },
    {
      id: "cmp_lgm_archi",
      name: "Architectes & Cabinets de design",
      platform: "LGM",
      status: "active",
      startDate: daysAgo(18),
      contactsTargeted: 210,
      messagesSent: 540,
      opened: 410,
      replied: 38,
      positiveReplies: 12,
      meetingsBooked: 4,
    },
    {
      id: "cmp_instantly_saas",
      name: "Cold Email — SaaS B2B Europe",
      platform: "Instantly",
      status: "active",
      startDate: daysAgo(25),
      contactsTargeted: 2500,
      messagesSent: 6800,
      opened: 2890,
      replied: 142,
      positiveReplies: 27,
      meetingsBooked: 7,
      notes: "3 variantes A/B testées — variante C performe le mieux (taux de réponse 2.9%).",
    },
    {
      id: "cmp_instantly_logistics",
      name: "Cold Email — Logistique & Supply Chain",
      platform: "Instantly",
      status: "paused",
      startDate: daysAgo(40),
      endDate: daysAgo(3),
      contactsTargeted: 1800,
      messagesSent: 4200,
      opened: 1680,
      replied: 64,
      positiveReplies: 11,
      meetingsBooked: 3,
    },
  ];
}

export function seedWebsites(): WebsiteProject[] {
  return [
    {
      id: "wp_verde",
      name: "Verde Bio Market",
      url: "https://verdebio.fr",
      companyId: "co_verde",
      monthlyVisitors: 4200,
      conversionRate: 2.8,
      avgLoadTime: 1.4,
      uptime: 99.98,
      lastChecked: daysAgo(0),
      status: "live",
    },
    {
      id: "wp_portfolio",
      name: "Mon portfolio freelance",
      url: "https://moncef-buri.dev",
      monthlyVisitors: 980,
      conversionRate: 4.1,
      avgLoadTime: 0.9,
      uptime: 100,
      lastChecked: daysAgo(0),
      status: "live",
    },
    {
      id: "wp_pulse",
      name: "Pulse Fitness Club",
      url: "https://pulsefitness.fr",
      companyId: "co_pulse",
      monthlyVisitors: 1650,
      conversionRate: 1.6,
      avgLoadTime: 2.7,
      uptime: 99.4,
      lastChecked: daysAgo(1),
      status: "issue",
    },
  ];
}

export function seedWorkflows(): Workflow[] {
  return [
    {
      id: "wf_new_lead",
      name: "Nouveau lead LGM → Séquence de qualification",
      trigger: "Contact créé avec source = LGM",
      active: true,
      createdAt: daysAgo(20),
      steps: [
        { id: uid(), type: "task", config: { title: "Recherche rapide LinkedIn", delayDays: "0" } },
        { id: uid(), type: "email", config: { template: "Intro personnalisée" } },
        { id: uid(), type: "wait", config: { days: "2" } },
        { id: uid(), type: "tag", config: { tag: "à qualifier" } },
      ],
    },
    {
      id: "wf_devis_sent",
      name: "Devis envoyé → Relance automatique",
      trigger: "Statut Devis = Envoyé",
      active: true,
      createdAt: daysAgo(10),
      steps: [
        { id: uid(), type: "wait", config: { days: "3" } },
        { id: uid(), type: "task", config: { title: "Relancer le client par email" } },
        { id: uid(), type: "wait", config: { days: "4" } },
        { id: uid(), type: "task", config: { title: "Appel de relance" } },
      ],
    },
    {
      id: "wf_deal_won",
      name: "Deal gagné → Onboarding client",
      trigger: "Stage Deal = Gagné",
      active: false,
      createdAt: daysAgo(5),
      steps: [
        { id: uid(), type: "stage_change", config: { status: "customer" } },
        { id: uid(), type: "email", config: { template: "Bienvenue + prochaines étapes" } },
        { id: uid(), type: "task", config: { title: "Planifier kickoff call" } },
      ],
    },
  ];
}
